website_project/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path("", views.main, name="root"),  # quotes:root
    path("<int:page>", views.main, name="root_paginate"),

    path("add_author/", views.add_author, name="add_author"),
    path("add_quote/", views.add_quote, name="add_quote"),

    path("my_authors/", views.my_authors, name="my_authors"),
    path("my_quotes/", views.my_quotes, name="my_quotes"),

    path('authors/<str:author_fullname>/', views.author_detail, name='author_info'),

    path('search/', views.search_results, name='search_results'),

    path('tag/<str:tag>/', views.quotes_by_tag, name='quotes_by_tag'),
]

website_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path("signin/",
         LoginView.as_view(template_name="users/login.html", form_class=LoginForm, redirect_authenticated_user=True),
         name="signin"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("logout-page/", views.UserLogoutPageView.as_view(), name="logout_page"),
    path('profile/', views.ProfileDetailView.as_view(), name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(template_name="users/password_reset.html"),
         name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete')]

website_project/website_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

website_project/quotes/models.py
from mongoengine import Document, StringField, DateTimeField, ListField, ReferenceField


class Author(Document):
    fullname = StringField(max_length=50, required=True)
    born_date = StringField(max_length=50, required=True)
    born_location = StringField(max_length=50, required=True)
    description = StringField(required=True)
    created_at = DateTimeField(max_length=50, required=True)


class Tag(Document):
    name = StringField(max_length=100, required=True, unique=True)


class Quote(Document):
    quote = StringField(required=True)
    tags = ListField(ReferenceField(Tag))
    author = ReferenceField(Author)
    created_at = DateTimeField(required=True)

website_project/quotes/forms.py
from django import forms
from django.forms import CharField, TextInput

from .utils import get_mongodb


class AuthorForm(forms.Form):
    fullname = CharField(max_length=50, widget=TextInput(attrs={"class": "form-control", "id": "exampleInputText1"}))
    born_date = CharField(max_length=50, widget=TextInput(attrs={"class": "form-control", "id": "exampleInputText2"}))
    born_location = CharField(max_length=150,
                              widget=TextInput(attrs={"class": "form-control", "id": "exampleInputText3"}))
    description = CharField(widget=TextInput(attrs={"class": "form-control", "id": "exampleInputText4"}))


class QuoteForm(forms.Form):
    quote = forms.CharField(max_length=50,
                            widget=forms.TextInput(attrs={"class": "form-control", "id": "exampleInputQuote1"}))

    tags = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "id": "exampleInputQuote2"}))

    author = forms.ChoiceField(choices=[],
                               widget=forms.Select(attrs={"class": "form-control", "id": "exampleInputQuote3"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        db = get_mongodb()
        authors_cursor = db.authors.find()
        authors = list(authors_cursor)

        author_choices = []
        for author in authors:
            author_choices.append((str(author["_id"]), author["fullname"]))
        try:
            self.fields['author'].choices = [("", "Select an author")] + author_choices
        except Exception as e:
            print("An error occurred during form initialization:", e)

        def clean_tags(self):
            """
            Custom validation to parse tags input into a list.
            """
            tags_input = self.cleaned_data['tags']
            if tags_input:
                # Split the input string by commas and strip whitespace from each tag
                tags_list = [tag.strip() for tag in tags_input.split(',')]
                return tags_list
            else:
                return []  # Return an empty list if no tags provided

website_project/quotes/views.py
from bson import ObjectId
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .utils import get_mongodb
from .forms import AuthorForm, QuoteForm


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)  # How many quotes per page
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={"quotes": quotes_on_page})


@login_required
def add_author(request):
    form = AuthorForm()
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            fullname = form.cleaned_data['fullname']
            born_date = form.cleaned_data['born_date']
            born_location = form.cleaned_data['born_location']
            description = form.cleaned_data['description']
            db = get_mongodb()
            db.authors.insert_one({"fullname": fullname, "born_date": born_date, "born_location": born_location,
                                   "description": description})
            return redirect(to="quotes:root")
    return render(request, "quotes/add_author.html", context={"form": form})


@login_required
def my_authors(request):
    db = get_mongodb()
    authors = db.authors.find()
    return render(request, "quotes/authors.html", context={"authors": authors})


@login_required
def add_quote(request):
    db = get_mongodb()
    authors = db.authors.find()
    authors_data = [{"id": str(author["_id"]), "fullname": author.get("fullname", "Unknown")} for author in authors]
    form = QuoteForm()

    if request.method == "POST":
        form = QuoteForm(request.POST)
        print(request.POST)
        if form.is_valid():
            quote_text = form.cleaned_data['quote']
            author_id = form.cleaned_data['author']
            author_id = ObjectId(author_id)

            tag_text = form.cleaned_data['tags']
            tags_list = [tag.strip() for tag in tag_text.split()]

            db.quotes.insert_one({"quote": quote_text, "tags": tags_list, "author": author_id})
            return redirect(to="quotes:root")
        else:
            print("Form is not valid:", form.errors)

    return render(request, "quotes/add_quote.html", context={"form": form, "authors": authors_data})


@login_required
def my_quotes(request):
    db = get_mongodb()
    quotes = db.quotes.find()

    return render(request, 'quotes/quotes.html', {'quotes': quotes})


def author_detail(request, author_fullname):
    db = get_mongodb()
    author = db.authors.find_one({"fullname": author_fullname})
    if author:
        quotes = list(db.quotes.find({"author": author["_id"]}))
        return render(request, "quotes/author_info.html", context={"author": author, "quotes": quotes})
    else:
        return HttpResponseNotFound("Author not found")


def search_results(request):
    db = get_mongodb()
    query = request.GET.get('q')
    if query:
        quotes = db.quotes.find({"quote": {"$regex": query, "$options": "i"}})
        results = list(quotes)

        return render(request, 'quotes/search_results.html', {'results': results, 'query': query})


def quotes_by_tag(request, tag):
    tag = tag.lower()
    db = get_mongodb()
    cursor = db.quotes.find({'tags': tag})
    print(cursor)
    quotes = list(cursor)
    print(quotes)
    return render(request, 'quotes/quotes_by_tag.html', {'quotes': quotes, 'tag': tag})

website_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-3">
    <h1 class="custom-h1">Add Author</h1>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form action="{% url 'quotes:add_author' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputText1" class="form-label">Fullname</label>
            {{ form.fullname }}

            <div id="textHelp1" class="form-text">Author's first and last name.</div>
            <span>{{form.errors.fullname}}</span>
        </div>
        <div class="mb-3">
            <label for="exampleInputText2" class="form-label">Born date</label>
            {{ form.born_date }}
            <div id="textHelp2" class="form-text">Author's date of birth.</div>
            <span>{{form.errors.born_date}}</span>
        </div>
        <div class="mb-3">
            <label for="exampleInputText3" class="form-label">Born location</label>
            {{ form.born_location }}
            <div id="textHelp3" class="form-text">Author's place of birth.</div>
            <span>{{form.errors.born_location}}</span>
        </div>
        <div class="mb-3">
            <label for="exampleInputText4" class="form-label">Description</label>
            {{ form.description }}
            <div id="textHelp4" class="form-text">Author's description.</div>
            <span>{{form.errors.description}}</span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

website_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block content %}
<div class="container mt-3">
    <h1 class="custom-h1">Add Quote</h1>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form action="{% url 'quotes:add_quote' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputQuote1" class="form-label">Quote</label>
            {{ form.quote }}
        </div>
        <div class="mb-3">
            <label for="exampleInputQuote2" class="form-label">Tags</label>
            {{ form.tags }}
            <div id="textHelp2" class="form-text">Quote Tags.</div>
            <span>{{form.errors.tags}}</span>
        </div>
        <div class="mb-3">
            <label for="exampleInputQuote3" class="form-label">Author</label>
            <select name="author" class="form-control" id="exampleInputQuote3" required="">
                <option value="">Select an author</option>
                {% for author in authors %}
                <option value="{{ author.id }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>

        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

website_project/quotes/templates/quotes/author_info.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="container mx-auto py-8">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="mb-4">
            <h2 class="custom-h2">{{author.fullname}}</h2>
            <strong>Born:</strong>
            <span class="author-born-date">{{author.born_date}}</span>
            <span class="author-born-location">{{author.born_location}}</span>
        </div>
        <div>
            <div class="mb-4">
                <h2 class="custom-h2">Description</h2>
                <p class="text-gray-600">{{author.description}}</p>
            </div>
            <div>

                <div class="mb-4">
                    <h3 class="text-xl font-semibold mb-2">Quotes by {{author.fullname}}</h3>
                    <ul>
                        {% for quote in quotes %}
                        <li class="mb-2">
                            <blockquote class="text-gray-800 italic border-l-4 border-blue-500 pl-4">
                                {{quote.quote}}
                            </blockquote>

                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Pagination -->
                <div class="flex justify-center">
                    <a href="#" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Previous
                    </a>
                    <a href="#" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2">
                        Next
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

website_project/quotes/templates/quotes/authors.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-3">
    <h1 class="custom-h1">My Authors</h1>
    {% for author in authors %}
    <div class="card mb-3">
        <div class="card-header">
            {{ forloop.counter }}. {{ author.names }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{author.fullname}}</h5>
            <p class="card-text">Born: {{author.born_date}} {{author.born_location}}</p>
            <a href="{% url 'quotes:author_info' author_fullname=author.fullname %}" class="btn btn-primary">About</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

website_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <title>Home Work</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none; font-weight: bold;">Quotes to Scrape</a>
            </h1>
        </div>

        <div class="col-md-4 text-end">
            <p>
                {% if user.is_authenticated %}
                <a href="/users/logout" class="btn btn-primary">Logout</a>
                {% else %}
                <a href="/users/signup" class="btn btn-primary">SignUp</a>
                <a href="/users/signin" class="btn btn-primary">Login</a>
                {% endif %}
            </p>
        </div>


    </div>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'quotes:root' %}">Home <span class="sr-only"></span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Menu
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'quotes:add_author' %}">Add Author</a>
                        <a class="dropdown-item" href="{% url 'quotes:add_quote' %}">Add Quote</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'quotes:my_authors' %}">My Authors</a>
                        <a class="dropdown-item" href="{% url 'quotes:my_quotes' %}">My Quotes</a>
                    </div>
                </li>
                {% endif %}

            </ul>
            <form class="row g-2 align-items-center" method="GET" action="{% url 'quotes:search_results' %}">
                <div class="col-auto">
                    <input class="form-control" type="search" name="q" placeholder="Search" aria-label="Search">
                </div>
                <div class="col-auto">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </div>
            </form>
        </div>
    </nav>

    {% block content %} {% endblock %}



    </div>
</div>

</body>
</html>

website_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/authors/{{quote.author|author}}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="{% url 'quotes:quotes_by_tag' tag=tag %}">{{tag}}</a>
                {% endfor %}
            </div>

        </div>

        {% endfor %}

        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>

    </div>

</div>

{% endblock %}

website_project/quotes/templates/quotes/quotes.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block content %}
<div class="container mt-3">
    <h1 class="custom-h1">My Quotes</h1>
    {% for quote in quotes %}

    <div class="card mb-3">
        <div class="card-header">
            {{ forloop.counter }}. {{ quote.author|author }}

        </div>

        <div class="card-body">
            <h5 class="card-title">{{quote.quote}}</h5>
            <p class="card-text">
                {% for tag in quote.tags.all %}
                <span class="tag">{{ tag.name }}</span>
                {% if not forloop.last %} {% endif %}
                {% endfor %}

            </p>

        </div>

    </div>

    {% endfor %}
</div>

{% endblock %}

website_project/quotes/templates/quotes/quotes_by_tag.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<h2>Quotes with tag "{{ tag }}"</h2>

{% for quote in quotes %}
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">
        {{quote.quote}}
    </span>
    <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
<a href="/authors/{{quote.author|author}}">(about)</a>
</span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags %}
        <a class="tag" href="{% url 'quotes:quotes_by_tag' tag=tag %}">{{tag}}</a>
        {% endfor %}
    </div>
</div>
{% endfor %}

{% endblock %}

website_project/quotes/templates/quotes/search_results.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<h2>Search Results</h2>
{% if query %}
<p>Showing results for: "{{ query }}"</p>
{% endif %}
<div class="quotes_list">
    {% for quote in results %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">
        {{quote.quote}}
    </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
<a href="/authors/{{quote.author|author}}">(about)</a>
</span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}
            <a class="tag" href="{% url 'quotes:quotes_by_tag' tag=tag %}">{{tag}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}